#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXAMPLE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$EXAMPLE_DIR/../.." && pwd)"

DRY_RUN=0
RESET=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    --reset) RESET=1 ;;
    -h|--help)
      cat <<'EOF'
Usage: scripts/setup_project.sh [--dry-run] [--reset]

Initializes the Docker file-reward example. Requires Docker for baseline
validation unless the project is only being dry-run inspected.
EOF
      exit 0
      ;;
    *)
      echo "unknown argument: $arg" >&2
      exit 2
      ;;
  esac
done

RUN_DIR="$EXAMPLE_DIR/.run"
SECRET_DIR="$RUN_DIR/secrets"
LOG_DIR="$RUN_DIR/logs"
REPORT_DIR="$RUN_DIR/reports"
WORKTREE_ROOT="$RUN_DIR/worktrees"
ALAB_EXAMPLE_HOME="${ALAB_EXAMPLE_HOME:-$RUN_DIR/alab-home}"
UV_CACHE_DIR="${UV_CACHE_DIR:-$RUN_DIR/uv-cache}"
UV_DEFAULT_INDEX="${UV_DEFAULT_INDEX:-https://pypi.org/simple}"
PYTHONPYCACHEPREFIX="${PYTHONPYCACHEPREFIX:-$RUN_DIR/pycache}"
ALAB_BIN="${ALAB_BIN:-uv run --frozen --project $REPO_ROOT alab}"
ALAB_CMD_PREFIX="UV_CACHE_DIR=$UV_CACHE_DIR UV_DEFAULT_INDEX=$UV_DEFAULT_INDEX PYTHONPYCACHEPREFIX=$PYTHONPYCACHEPREFIX $ALAB_BIN --home $ALAB_EXAMPLE_HOME"
PROJECT_ENV="$SECRET_DIR/project.env"

read -r -a ALAB_CMD <<< "$ALAB_BIN"
run_alab() {
  UV_CACHE_DIR="$UV_CACHE_DIR" UV_DEFAULT_INDEX="$UV_DEFAULT_INDEX" PYTHONPYCACHEPREFIX="$PYTHONPYCACHEPREFIX" "${ALAB_CMD[@]}" --home "$ALAB_EXAMPLE_HOME" "$@"
}
extract_field_text() {
  local label="$1"
  awk -v key="$label" 'index($0, key ": ") == 1 { print substr($0, length(key) + 3); exit }'
}

if [[ "$DRY_RUN" == "1" ]]; then
  cat <<EOF
Would initialize the Docker file-reward example.

ALAB home:    $ALAB_EXAMPLE_HOME
Project env:  $PROJECT_ENV
Dockerfile:   $EXAMPLE_DIR/source/Dockerfile
uv index:     $UV_DEFAULT_INDEX
EOF
  exit 0
fi

if [[ "$RESET" == "1" ]]; then
  rm -rf "$RUN_DIR"
fi
mkdir -p "$SECRET_DIR" "$LOG_DIR" "$REPORT_DIR" "$WORKTREE_ROOT" "$UV_CACHE_DIR" "$PYTHONPYCACHEPREFIX"
if [[ -f "$PROJECT_ENV" ]]; then
  echo "Existing project env found: $PROJECT_ENV"
  echo "Use --reset to recreate the example from scratch."
  exit 0
fi
if [[ "$ALAB_BIN" == uv\ * ]] && ! command -v uv >/dev/null 2>&1; then
  echo "missing uv CLI; install uv or set ALAB_BIN to an installed alab command" >&2
  exit 1
fi
if ! command -v docker >/dev/null 2>&1; then
  echo "missing docker CLI; install/start Docker before running this example" >&2
  exit 1
fi

AUTH_OUTPUT="$(run_alab auth init)"
ROOT_KEY="$(printf '%s\n' "$AUTH_OUTPUT" | extract_field_text "root key")"
printf '%s\n' "${AUTH_OUTPUT//$ROOT_KEY/<root-key>}" | tee "$LOG_DIR/01-auth-init.redacted.log"

set +e
PROJECT_OUTPUT="$(run_alab --key "$ROOT_KEY" project init local --config "$EXAMPLE_DIR/alab.project.toml" --source-path "$EXAMPLE_DIR/source" 2>&1)"
PROJECT_STATUS=$?
set -e
PROJECT_ID="$(printf '%s\n' "$PROJECT_OUTPUT" | extract_field_text "project id")"
PROJECT_KEY="$(printf '%s\n' "$PROJECT_OUTPUT" | extract_field_text "admin key")"
VALIDATION_STATUS="$(printf '%s\n' "$PROJECT_OUTPUT" | extract_field_text "validation status")"
printf '%s\n' "${PROJECT_OUTPUT//$PROJECT_KEY/<project-admin-key>}" | tee "$LOG_DIR/02-project-init.redacted.log"

if [[ -z "$PROJECT_ID" || -z "$PROJECT_KEY" ]]; then
  echo "failed to parse project id or admin key; inspect $LOG_DIR/02-project-init.redacted.log" >&2
  exit "$PROJECT_STATUS"
fi

{
  printf '# Generated by docker_file_reward_artifacts/scripts/setup_project.sh\n'
  printf '# Ignored by git. Do not commit.\n'
  printf 'export ALAB_EXAMPLE_HOME=%q\n' "$ALAB_EXAMPLE_HOME"
  printf 'export ALAB_PROJECT_ID=%q\n' "$PROJECT_ID"
  printf 'export ALAB_PROJECT_KEY=%q\n' "$PROJECT_KEY"
  printf 'export ALAB_BIN=%q\n' "$ALAB_BIN"
  printf 'export ALAB_CMD_PREFIX=%q\n' "$ALAB_CMD_PREFIX"
  printf 'export UV_CACHE_DIR=%q\n' "$UV_CACHE_DIR"
  printf 'export UV_DEFAULT_INDEX=%q\n' "$UV_DEFAULT_INDEX"
  printf 'export PYTHONPYCACHEPREFIX=%q\n' "$PYTHONPYCACHEPREFIX"
  printf 'export ALAB_REPORT_DIR=%q\n' "$REPORT_DIR"
  printf 'export ALAB_EXAMPLE_WORKTREE_ROOT=%q\n' "$WORKTREE_ROOT"
} > "$PROJECT_ENV"
chmod 600 "$PROJECT_ENV"

echo "Project initialized: $PROJECT_ID"
echo "Validation status: $VALIDATION_STATUS"
exit "$PROJECT_STATUS"
