from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass

from .feedback import cmd_feedback, cmd_feedback_archive, cmd_feedback_list, cmd_feedback_show
from .rendering import ResultBlock
from .services import (
    LongRunningResult,
    Request,
    cmd_annotate_add,
    cmd_annotate_archive,
    cmd_annotate_edit,
    cmd_annotate_remove,
    cmd_annotate_unarchive,
    cmd_audit_list,
    cmd_audit_show,
    cmd_auth_init,
    cmd_auth_root_regenerate,
    cmd_backup_prune,
    cmd_cache_prune,
    cmd_catalog_skydiscover_add,
    cmd_catalog_skydiscover_remove,
    cmd_catalog_skydiscover_show,
    cmd_catalog_skydiscover_update,
    cmd_config_reset,
    cmd_config_set,
    cmd_config_show,
    cmd_config_validate,
    cmd_context_repair,
    cmd_context_show,
    cmd_dashboard,
    cmd_exp_archive,
    cmd_exp_best,
    cmd_exp_checkout,
    cmd_exp_checkout_remove,
    cmd_exp_create,
    cmd_exp_list,
    cmd_exp_remove,
    cmd_exp_search,
    cmd_exp_show,
    cmd_exp_tag_add,
    cmd_exp_tag_list,
    cmd_exp_tag_remove,
    cmd_exp_token_list,
    cmd_exp_token_regenerate,
    cmd_exp_token_revoke,
    cmd_exp_unarchive,
    cmd_exp_worktree_remove,
    cmd_exp_worktree_restore,
    cmd_help,
    cmd_key_create,
    cmd_key_list,
    cmd_key_revoke,
    cmd_observe_annotations_list,
    cmd_observe_annotations_show,
    cmd_observe_artifacts_archive,
    cmd_observe_artifacts_export,
    cmd_observe_artifacts_list,
    cmd_observe_artifacts_remove,
    cmd_observe_artifacts_show,
    cmd_observe_artifacts_unarchive,
    cmd_observe_logs_archive,
    cmd_observe_logs_export,
    cmd_observe_logs_list,
    cmd_observe_logs_remove,
    cmd_observe_logs_show,
    cmd_observe_logs_unarchive,
    cmd_observe_runs_archive,
    cmd_observe_runs_list,
    cmd_observe_runs_remove,
    cmd_observe_runs_show,
    cmd_observe_runs_unarchive,
    cmd_project_archive,
    cmd_project_config_export,
    cmd_project_config_import,
    cmd_project_config_set,
    cmd_project_config_show,
    cmd_project_env_list,
    cmd_project_env_set,
    cmd_project_env_unset,
    cmd_project_init,
    cmd_project_list,
    cmd_project_locks_clear_stale,
    cmd_project_remove,
    cmd_project_secret_gc,
    cmd_project_secret_list,
    cmd_project_secret_set,
    cmd_project_secret_unset,
    cmd_project_show,
    cmd_project_unarchive,
    cmd_project_validate,
    cmd_project_validation_archive,
    cmd_project_validation_remove,
    cmd_project_validation_unarchive,
    cmd_report,
    cmd_run,
    cmd_source_archive,
    cmd_source_import,
    cmd_source_list,
    cmd_source_remove,
    cmd_source_show,
    cmd_source_unarchive,
    cmd_status,
    cmd_submit,
)

Handler = Callable[[list[str], Request], list[ResultBlock] | LongRunningResult]


@dataclass(frozen=True)
class CommandSpec:
    path: tuple[str, ...]
    object_type: str
    summary: str
    credential: str
    handler: Handler


def _spec(path: str, object_type: str, summary: str, credential: str, handler: Handler) -> CommandSpec:
    return CommandSpec(tuple(path.split()), object_type, summary, credential, handler)


COMMANDS: list[CommandSpec] = [
    _spec("help", "help", "Show context-aware command help.", "none", cmd_help),
    _spec("auth init", "auth", "Initialize ALab home and root key.", "none", cmd_auth_init),
    _spec("auth root regenerate", "auth", "Regenerate the root key.", "root", cmd_auth_root_regenerate),
    _spec("config show", "config", "Show global configuration.", "none", cmd_config_show),
    _spec("config set", "config", "Set a global configuration field.", "none", cmd_config_set),
    _spec("config reset", "config", "Reset global configuration.", "none", cmd_config_reset),
    _spec("config validate", "config", "Validate global configuration.", "none", cmd_config_validate),
    _spec("context show", "context", "Show context marker and registry status.", "none", cmd_context_show),
    _spec("context repair", "context", "Repair context path registry entries.", "none", cmd_context_repair),
    _spec("feedback", "feedback", "Submit local agent feedback into ALab home.", "none", cmd_feedback),
    _spec("feedback list", "feedback", "List HOME-level feedback records.", "root", cmd_feedback_list),
    _spec("feedback show", "feedback", "Show a HOME-level feedback record.", "root", cmd_feedback_show),
    _spec("feedback archive", "feedback", "Archive a HOME-level feedback record.", "root", cmd_feedback_archive),
    _spec("dashboard", "dashboard", "Open the root-only local read-only dashboard.", "root", cmd_dashboard),
    _spec("report", "report", "Export a Markdown project or experiment evidence report.", "token_or_admin", cmd_report),
    _spec("key create", "credential", "Create a project admin key.", "root", cmd_key_create),
    _spec("key list", "credential", "List root or project admin keys.", "admin", cmd_key_list),
    _spec("key revoke", "credential", "Revoke a credential.", "root", cmd_key_revoke),
    _spec("project init", "project", "Create a project from local, Git, empty, or adapter source.", "root", cmd_project_init),
    _spec("project list", "project", "List projects.", "root", cmd_project_list),
    _spec("project show", "project", "Show project details.", "admin", cmd_project_show),
    _spec("project archive", "project", "Archive a project.", "admin", cmd_project_archive),
    _spec("project unarchive", "project", "Unarchive a project.", "admin", cmd_project_unarchive),
    _spec("project remove", "project", "Remove an archived project.", "root", cmd_project_remove),
    _spec("project config show", "project_config", "Show project configuration.", "admin", cmd_project_config_show),
    _spec("project config export", "project_config", "Export project configuration TOML.", "admin", cmd_project_config_export),
    _spec("project config import", "project_config", "Import project configuration TOML.", "admin", cmd_project_config_import),
    _spec("project config set", "project_config", "Set a project configuration field.", "admin", cmd_project_config_set),
    _spec("project env set", "project_env", "Set a project environment variable.", "admin", cmd_project_env_set),
    _spec("project env unset", "project_env", "Unset a project environment variable.", "admin", cmd_project_env_unset),
    _spec("project env list", "project_env", "List project environment variables.", "admin", cmd_project_env_list),
    _spec("project secret set", "project_secret", "Set a project secret.", "admin", cmd_project_secret_set),
    _spec("project secret unset", "project_secret", "Unset a project secret.", "admin", cmd_project_secret_unset),
    _spec("project secret list", "project_secret", "List project secret fingerprints.", "admin", cmd_project_secret_list),
    _spec("project secret gc", "project_secret", "Delete unreferenced raw secret values.", "admin", cmd_project_secret_gc),
    _spec("project validate", "validation", "Validate the latest project config.", "admin", cmd_project_validate),
    _spec("project validation archive", "validation", "Archive a project validation.", "admin", cmd_project_validation_archive),
    _spec("project validation unarchive", "validation", "Unarchive a project validation.", "admin", cmd_project_validation_unarchive),
    _spec("project validation remove", "validation", "Remove an archived project validation.", "admin", cmd_project_validation_remove),
    _spec("project locks clear-stale", "lock_clear", "Clear expired project locks.", "admin", cmd_project_locks_clear_stale),
    _spec("status", "project", "Show context status.", "public", cmd_status),
    _spec("source import", "source", "Import a source snapshot.", "admin", cmd_source_import),
    _spec("source list", "source", "List project sources.", "admin", cmd_source_list),
    _spec("source show", "source", "Show source details.", "admin", cmd_source_show),
    _spec("source archive", "source", "Archive a source.", "admin", cmd_source_archive),
    _spec("source unarchive", "source", "Unarchive a source.", "admin", cmd_source_unarchive),
    _spec("source remove", "source", "Remove an archived source.", "admin", cmd_source_remove),
    _spec("exp create", "experiment", "Create an experiment worktree.", "public_or_admin", cmd_exp_create),
    _spec("exp list", "experiment", "List experiments.", "token_or_admin", cmd_exp_list),
    _spec("exp search", "experiment", "Search visible experiments.", "token_or_admin", cmd_exp_search),
    _spec("exp show", "experiment", "Show a visible experiment.", "token_or_admin", cmd_exp_show),
    _spec("exp best", "experiment", "Rank visible experiments by best run reward.", "token_or_admin", cmd_exp_best),
    _spec("exp archive", "experiment", "Archive an experiment.", "admin", cmd_exp_archive),
    _spec("exp unarchive", "experiment", "Unarchive an experiment.", "admin", cmd_exp_unarchive),
    _spec("exp remove", "experiment", "Remove an archived experiment.", "admin", cmd_exp_remove),
    _spec("exp checkout", "inspection_checkout", "Create an inspection checkout.", "token_or_admin", cmd_exp_checkout),
    _spec("exp checkout remove", "inspection_checkout", "Remove an inspection checkout.", "token_or_admin", cmd_exp_checkout_remove),
    _spec("exp worktree remove", "worktree", "Remove an experiment worktree.", "admin", cmd_exp_worktree_remove),
    _spec("exp worktree restore", "worktree", "Restore an experiment worktree.", "admin", cmd_exp_worktree_restore),
    _spec("exp token list", "credential", "List experiment tokens.", "admin", cmd_exp_token_list),
    _spec("exp token revoke", "credential", "Revoke experiment tokens.", "admin", cmd_exp_token_revoke),
    _spec("exp token regenerate", "credential", "Regenerate an experiment token.", "admin", cmd_exp_token_regenerate),
    _spec("exp tag add", "tag", "Add an experiment tag.", "token_or_admin", cmd_exp_tag_add),
    _spec("exp tag remove", "tag", "Remove an experiment tag.", "token_or_admin", cmd_exp_tag_remove),
    _spec("exp tag list", "tag", "List experiment tags.", "token_or_admin", cmd_exp_tag_list),
    _spec("observe experiments list", "experiment", "List visible experiments.", "token_or_admin", cmd_exp_list),
    _spec("observe experiments search", "experiment", "Search visible experiments.", "token_or_admin", cmd_exp_search),
    _spec("observe experiments show", "experiment", "Show a visible experiment.", "token_or_admin", cmd_exp_show),
    _spec("observe experiments best", "experiment", "Rank visible experiments by best run reward.", "token_or_admin", cmd_exp_best),
    _spec("observe runs list", "run", "List visible runs.", "token_or_admin", cmd_observe_runs_list),
    _spec("observe runs show", "run", "Show a visible run.", "token_or_admin", cmd_observe_runs_show),
    _spec("observe runs archive", "run", "Archive a run.", "token_or_admin", cmd_observe_runs_archive),
    _spec("observe runs unarchive", "run", "Unarchive a run.", "token_or_admin", cmd_observe_runs_unarchive),
    _spec("observe runs remove", "run", "Remove an archived run.", "admin", cmd_observe_runs_remove),
    _spec("observe artifacts list", "artifact", "List visible artifacts.", "token_or_admin", cmd_observe_artifacts_list),
    _spec("observe artifacts show", "artifact", "Show a visible artifact.", "token_or_admin", cmd_observe_artifacts_show),
    _spec("observe artifacts export", "artifact", "Export captured artifact bytes.", "token_or_admin", cmd_observe_artifacts_export),
    _spec("observe artifacts archive", "artifact", "Archive an artifact.", "token_or_admin", cmd_observe_artifacts_archive),
    _spec("observe artifacts unarchive", "artifact", "Unarchive an artifact.", "token_or_admin", cmd_observe_artifacts_unarchive),
    _spec("observe artifacts remove", "artifact", "Remove an archived artifact.", "admin", cmd_observe_artifacts_remove),
    _spec("observe logs list", "log", "List visible logs.", "token_or_admin", cmd_observe_logs_list),
    _spec("observe logs show", "log", "Show a visible log.", "token_or_admin", cmd_observe_logs_show),
    _spec("observe logs export", "log", "Export captured log bytes.", "token_or_admin", cmd_observe_logs_export),
    _spec("observe logs archive", "log", "Archive a log.", "token_or_admin", cmd_observe_logs_archive),
    _spec("observe logs unarchive", "log", "Unarchive a log.", "token_or_admin", cmd_observe_logs_unarchive),
    _spec("observe logs remove", "log", "Remove an archived log.", "admin", cmd_observe_logs_remove),
    _spec("observe annotations list", "annotation", "List visible annotations.", "token_or_admin", cmd_observe_annotations_list),
    _spec("observe annotations show", "annotation", "Show a visible annotation.", "token_or_admin", cmd_observe_annotations_show),
    _spec("runs list", "run", "List visible runs.", "token_or_admin", cmd_observe_runs_list),
    _spec("runs show", "run", "Show a visible run.", "token_or_admin", cmd_observe_runs_show),
    _spec("runs archive", "run", "Archive a run.", "token_or_admin", cmd_observe_runs_archive),
    _spec("runs unarchive", "run", "Unarchive a run.", "token_or_admin", cmd_observe_runs_unarchive),
    _spec("runs remove", "run", "Remove an archived run.", "admin", cmd_observe_runs_remove),
    _spec("artifacts list", "artifact", "List visible artifacts.", "token_or_admin", cmd_observe_artifacts_list),
    _spec("artifacts show", "artifact", "Show a visible artifact.", "token_or_admin", cmd_observe_artifacts_show),
    _spec("artifacts export", "artifact", "Export captured artifact bytes.", "token_or_admin", cmd_observe_artifacts_export),
    _spec("artifacts archive", "artifact", "Archive an artifact.", "token_or_admin", cmd_observe_artifacts_archive),
    _spec("artifacts unarchive", "artifact", "Unarchive an artifact.", "token_or_admin", cmd_observe_artifacts_unarchive),
    _spec("artifacts remove", "artifact", "Remove an archived artifact.", "admin", cmd_observe_artifacts_remove),
    _spec("logs list", "log", "List visible logs.", "token_or_admin", cmd_observe_logs_list),
    _spec("logs show", "log", "Show a visible log.", "token_or_admin", cmd_observe_logs_show),
    _spec("logs export", "log", "Export captured log bytes.", "token_or_admin", cmd_observe_logs_export),
    _spec("logs archive", "log", "Archive a log.", "token_or_admin", cmd_observe_logs_archive),
    _spec("logs unarchive", "log", "Unarchive a log.", "token_or_admin", cmd_observe_logs_unarchive),
    _spec("logs remove", "log", "Remove an archived log.", "admin", cmd_observe_logs_remove),
    _spec("annotations list", "annotation", "List visible annotations.", "token_or_admin", cmd_observe_annotations_list),
    _spec("annotations show", "annotation", "Show a visible annotation.", "token_or_admin", cmd_observe_annotations_show),
    _spec("annotate add", "annotation", "Add an annotation.", "token_or_admin", cmd_annotate_add),
    _spec("annotate edit", "annotation", "Edit an annotation.", "token_or_admin", cmd_annotate_edit),
    _spec("annotate archive", "annotation", "Archive an annotation.", "token_or_admin", cmd_annotate_archive),
    _spec("annotate unarchive", "annotation", "Unarchive an annotation.", "token_or_admin", cmd_annotate_unarchive),
    _spec("annotate remove", "annotation", "Remove an archived annotation.", "token_or_admin", cmd_annotate_remove),
    _spec("run", "run", "Run the bound runner in an experiment.", "token", cmd_run),
    _spec("submit", "submission", "Submit a final experiment result.", "token", cmd_submit),
    _spec("audit list", "audit", "List lifecycle audit events.", "root", cmd_audit_list),
    _spec("audit show", "audit", "Show one lifecycle audit event.", "root", cmd_audit_show),
    _spec("backup prune", "backup_prune", "Prune migration backups.", "root", cmd_backup_prune),
    _spec("cache prune", "cache_prune", "Prune rebuildable local caches.", "root", cmd_cache_prune),
    _spec("catalog skydiscover add", "catalog", "Add and pin the SkyDiscover catalog.", "root", cmd_catalog_skydiscover_add),
    _spec("catalog skydiscover update", "catalog", "Update and pin the SkyDiscover catalog.", "root", cmd_catalog_skydiscover_update),
    _spec("catalog skydiscover show", "catalog", "Show the active SkyDiscover catalog.", "root", cmd_catalog_skydiscover_show),
    _spec("catalog skydiscover remove", "catalog", "Remove the active SkyDiscover catalog.", "root", cmd_catalog_skydiscover_remove),
]


COMMANDS_BY_PATH = {spec.path: spec for spec in COMMANDS}


def match_command(argv: list[str]) -> tuple[CommandSpec | None, list[str]]:
    best: CommandSpec | None = None
    best_len = 0
    for spec in COMMANDS:
        n = len(spec.path)
        if len(argv) >= n and tuple(argv[:n]) == spec.path and n > best_len:
            best = spec
            best_len = n
    if best is None:
        return None, argv
    return best, argv[best_len:]
