#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXAMPLE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$EXAMPLE_DIR/../.." && pwd)"

DRY_RUN=0
RESET=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    --reset) RESET=1 ;;
    -h|--help)
      cat <<'EOF'
Usage: scripts/setup_project.sh [--dry-run] [--reset]

Initializes an isolated ALab home, pins the official SkyDiscover catalog, and
creates the Circle Packing project. The generated project admin key is written
only to ignored .run/project.env.
EOF
      exit 0
      ;;
    *)
      echo "unknown argument: $arg" >&2
      exit 2
      ;;
  esac
done

RUN_DIR="$EXAMPLE_DIR/.run"
LOG_DIR="$RUN_DIR/logs"
ALAB_EXAMPLE_HOME="${ALAB_EXAMPLE_HOME:-$RUN_DIR/alab-home}"
UV_CACHE_DIR="${UV_CACHE_DIR:-$RUN_DIR/uv-cache}"
PYTHONPYCACHEPREFIX="${PYTHONPYCACHEPREFIX:-$RUN_DIR/pycache}"
SKYDISCOVER_COMMIT="${SKYDISCOVER_COMMIT:-c0f6b704a05d883b61eff261023f61897cb45711}"
ALAB_BIN="${ALAB_BIN:-uv run --frozen --project $REPO_ROOT alab}"
ALAB_CMD_PREFIX="UV_CACHE_DIR=$UV_CACHE_DIR PYTHONPYCACHEPREFIX=$PYTHONPYCACHEPREFIX $ALAB_BIN --home $ALAB_EXAMPLE_HOME"
PROJECT_ENV="$RUN_DIR/project.env"
CONFIG_PATH="$EXAMPLE_DIR/alab.project.toml"

read -r -a ALAB_CMD <<< "$ALAB_BIN"

run_alab() {
  UV_CACHE_DIR="$UV_CACHE_DIR" PYTHONPYCACHEPREFIX="$PYTHONPYCACHEPREFIX" "${ALAB_CMD[@]}" --home "$ALAB_EXAMPLE_HOME" "$@"
}

extract_field_text() {
  local label="$1"
  awk -v key="$label" 'index($0, key ": ") == 1 { print substr($0, length(key) + 3); exit }'
}

if [[ "$DRY_RUN" == "1" ]]; then
  cat <<EOF
Would initialize the ALab Circle Packing example.

Example directory: $EXAMPLE_DIR
ALAB home:         $ALAB_EXAMPLE_HOME
Catalog commit:    $SKYDISCOVER_COMMIT
ALAB command:      $ALAB_CMD_PREFIX

Commands:
  $ALAB_CMD_PREFIX auth init
  $ALAB_CMD_PREFIX --key <root-key> catalog skydiscover add --commit $SKYDISCOVER_COMMIT
  $ALAB_CMD_PREFIX --key <root-key> project init skydiscover --config $CONFIG_PATH

Generated files stay under ignored .run/.
EOF
  exit 0
fi

if [[ "$RESET" == "1" ]]; then
  rm -rf "$RUN_DIR"
fi

mkdir -p "$LOG_DIR"

if [[ -f "$PROJECT_ENV" ]]; then
  echo "Existing project env found: $PROJECT_ENV"
  echo "Use --reset to recreate the example from scratch."
  exit 0
fi

AUTH_LOG="$LOG_DIR/01-auth-init.redacted.log"
CATALOG_LOG="$LOG_DIR/02-catalog-add.log"
PROJECT_REDACTED_LOG="$LOG_DIR/03-project-init.redacted.log"

set +e
AUTH_OUTPUT="$(run_alab auth init 2>&1)"
AUTH_STATUS=$?
set -e
if [[ "$AUTH_STATUS" != "0" ]]; then
  printf '%s\n' "$AUTH_OUTPUT"
  exit "$AUTH_STATUS"
fi
ROOT_KEY="$(printf '%s\n' "$AUTH_OUTPUT" | extract_field_text "root key")"
if [[ -z "$ROOT_KEY" ]]; then
  echo "failed to parse root key from auth init output" >&2
  exit 1
fi
printf '%s\n' "${AUTH_OUTPUT//$ROOT_KEY/<root-key>}" > "$AUTH_LOG"
cat "$AUTH_LOG"

run_alab --key "$ROOT_KEY" catalog skydiscover add --commit "$SKYDISCOVER_COMMIT" | tee "$CATALOG_LOG"
set +e
PROJECT_OUTPUT="$(run_alab --key "$ROOT_KEY" project init skydiscover --config "$CONFIG_PATH" 2>&1)"
PROJECT_STATUS=$?
set -e

PROJECT_ID="$(printf '%s\n' "$PROJECT_OUTPUT" | extract_field_text "project id")"
PROJECT_KEY="$(printf '%s\n' "$PROJECT_OUTPUT" | extract_field_text "admin key")"
VALIDATION_ID="$(printf '%s\n' "$PROJECT_OUTPUT" | extract_field_text "validation id")"
VALIDATION_STATUS="$(printf '%s\n' "$PROJECT_OUTPUT" | extract_field_text "validation status")"

if [[ -z "$PROJECT_ID" || -z "$PROJECT_KEY" ]]; then
  echo "failed to parse project id or admin key from project init output" >&2
  exit 1
fi

printf '%s\n' "${PROJECT_OUTPUT//$PROJECT_KEY/<project-admin-key>}" > "$PROJECT_REDACTED_LOG"
cat "$PROJECT_REDACTED_LOG"

{
  printf '# Generated by examples/skydiscover_circle_packing_codex/scripts/setup_project.sh\n'
  printf '# This file is ignored by git. Do not commit it.\n'
  printf 'export ALAB_EXAMPLE_HOME=%q\n' "$ALAB_EXAMPLE_HOME"
  printf 'export ALAB_PROJECT_ID=%q\n' "$PROJECT_ID"
  printf 'export ALAB_PROJECT_KEY=%q\n' "$PROJECT_KEY"
  printf 'export ALAB_BIN=%q\n' "$ALAB_BIN"
  printf 'export ALAB_CMD_PREFIX=%q\n' "$ALAB_CMD_PREFIX"
  printf 'export UV_CACHE_DIR=%q\n' "$UV_CACHE_DIR"
  printf 'export PYTHONPYCACHEPREFIX=%q\n' "$PYTHONPYCACHEPREFIX"
  printf 'export SKYDISCOVER_COMMIT=%q\n' "$SKYDISCOVER_COMMIT"
  printf 'export ALAB_EXAMPLE_DIR=%q\n' "$EXAMPLE_DIR"
} > "$PROJECT_ENV"
chmod 600 "$PROJECT_ENV"

cat > "$RUN_DIR/setup-summary.md" <<EOF
# Setup Summary

- Project id: \`$PROJECT_ID\`
- Validation id: \`$VALIDATION_ID\`
- Validation status: \`$VALIDATION_STATUS\`
- SkyDiscover commit: \`$SKYDISCOVER_COMMIT\`
- Project env: \`.run/project.env\` (contains the project admin key; ignored)
- Redacted init log: \`.run/logs/03-project-init.redacted.log\`
EOF

echo "Project initialized: $PROJECT_ID"
echo "Validation status: $VALIDATION_STATUS"
echo "Source .run/project.env before running worker/controller scripts."
if [[ "$PROJECT_STATUS" != "0" ]]; then
  echo "project init exited with status $PROJECT_STATUS; inspect $PROJECT_REDACTED_LOG" >&2
  exit "$PROJECT_STATUS"
fi
